####################################
# Port & Project Name
####################################
server:
  port: 8080                    # 포트 번호
  servlet:
    encoding:
      charset: UTF-8
      force: true

file:
    # upload-dir: C:/IntelliJ_WS/pf-uploads
    upload-dir: ${PF_UPLOAD_DIR:${user.home}/pf-uploads}       # 파일 업로드 경로

spring:
  application:
    name: pf

  output:
    ansi:
      enabled: ALWAYS            # 콘솔 출력 시 ANSI 컬러 코드를 항상 사용

  messages:
    basename: messages
    encoding: UTF-8

  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true

  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false

  ####################################
  # MySQL 설정
  ####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pf_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  ####################################
  # JPA 설정
  ####################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update      # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # 카멜케이스를 언더스코어로 변환
    show-sql: true          # SQL 출력 여부
    properties:
      hibernate:
        format_sql: true    # SQL 포맷팅 여부

  ####################################
  # Security User 설정
  ####################################
#  security:
#    user:
#      name: test
#      password: 1111
#      roles: USER

####################################
# Logging 설정
####################################
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        orm:
          jdbc:
            bind: trace